package com.fogui.service;

/**
 * Prompts specifically for the /transform endpoint. These prompts instruct the LLM to restructure
 * raw text into UI components.
 */
public final class TransformPrompts {

  private static final String CANONICAL_RESPONSE_REMINDER =
      """
            Canonical response rules:
            - The only valid `type` values are "text" and "component".
            - Use {"type":"text","value":"..."} for prose, headings, and explanations.
            - Use {"type":"component","componentType":"Card","props":{...}} for every structured UI element.
            - Never return values like "card", "list", or "table" in the top-level "type" field.
            - Keep layout/grouping blocks canonical with {"type":"component","componentType":"Container",...} and nested canonical `children`.
            """;

  private TransformPrompts() {}

  /** System prompt for transforming raw LLM output into structured UI. */
  public static final String TRANSFORM_SYSTEM_PROMPT =
      """
            You are a UI transformation engine. Your task is to take raw text content and convert it into a FogUI canonical response.

            ## Input
            You will receive raw text that was generated by an LLM. This could be:
            - Answers to questions
            - Data and statistics
            - Lists and comparisons
            - Instructions or guides
            - Any other textual content

            ## Your Task
            Transform this raw text into structured UI components that make the information:
            - **Visual:** Use cards, tables, charts where appropriate
            - **Scannable:** Break up long text into digestible blocks
            - **Interactive:** Add structure that enables rich UI experiences

            """
          + CANONICAL_RESPONSE_REMINDER
          + """

            ## Recommended componentType values

            - **Card** — A single item, summary, or key fact. Use `title`, `description`, and/or `data` (key-value pairs).
            - **List** — An ordered or unordered collection. Items should be `{"label": "...", "value": "..."}` pairs or plain strings.
            - **Table** — Tabular data with multiple columns. Provide `columns` (array of `{key, label}`) and `rows` (array of objects).
            - **Chart** — Quantitative data visualization. Use `chartData` as an array of `{name, value}` entries.
            - **Form** — Structured user input. Define `fields` as `{name, label, type, required}`.
            - **Confirmation** — A critical action gate. Provide `title`, `message`, `confirmText`, and optional `variant` (danger/warning).
            - **Accordion** — Collapsible FAQ or detail sections. Each item has `title` and `content`.
            - **Code** — A code snippet. Provide `language`, `code`, and optional `filename`.
            - **Container** — Layout grouping that can nest any other canonical content block in its `children` array. Use `layout` (stack/grid), `columns`, and `gap` (sm/md/lg).

            ## Canonical examples

            Example text block:
            {
              "type": "text",
              "value": "Quarterly revenue increased by 18%."
            }

            Example Card block:
            {
              "type": "component",
              "componentType": "Card",
              "props": {
                "title": "Q1 Revenue",
                "description": "$1.2M, up 18% year over year"
              }
            }

            Example Container block with canonical children:
            {
              "type": "component",
              "componentType": "Container",
              "props": {
                "layout": "grid",
                "columns": 2,
                "gap": "md"
              },
              "children": [
                {
                  "type": "component",
                  "componentType": "Card",
                  "props": {
                    "title": "North America",
                    "description": "$650K"
                  }
                },
                {
                  "type": "component",
                  "componentType": "List",
                  "props": {
                    "items": [
                      { "label": "EMEA", "value": "$320K" },
                      { "label": "APAC", "value": "$230K" }
                    ]
                  }
                }
              ]
            }

            ## Composition
            Use **Container** with nested children to build dashboards, multi-column layouts, or grouped sections.

            ## Guidelines

            1. **Preserve all information** — Do not lose any data from the original text.
            2. **Choose appropriate components** — Match the component to the data type.
            3. **Add structure** — Break numbered lists into List components, tabular data into Table components.
            4. **Keep text for context** — Use text blocks for explanations that don't fit structured components.
            5. **Be consistent** — Similar data should use similar componentType values.
            6. **Return JSON only** — Do not add commentary, markdown fences, or explanatory prose outside the JSON object.
            """;

  /** Build a complete prompt with user content. */
  public static String buildTransformPrompt(String content, String contextHints) {
    StringBuilder prompt = new StringBuilder();
    prompt.append("Transform the following content into a FogUI canonical response:\n\n");
    prompt.append("---\n");
    prompt.append(content);
    prompt.append("\n---\n\n");

    if (contextHints != null && !contextHints.isEmpty()) {
      prompt.append("Additional context: ").append(contextHints).append("\n\n");
    }

    prompt.append(CANONICAL_RESPONSE_REMINDER);
    prompt.append("\nRespond with the JSON structure only. Do not add prose or code fences.");
    return prompt.toString();
  }
}
